### ISSUE TITLE
`group-hover` is not supported in attributify mode

### ISSUE THREAD

**Issue by neal2018** [windicss/windicss#308]
Hey, I do not know whether it is intended or not, but it would be nice to support `group-hover` in attributify mode.

In following code
```html
<template>
  <div class="group">
    <p group-hover="bg-red-900">Hello</p>
  </div>
</template>
```
Vite would raise error
```sh
11:12:02 PM [vite] Internal server error: _this._variants[i] is not a function
      at C:\Users\neal\Projects\vite-test\node_modules\windicss\lib\index.js:9516:62
      at Array.map (<anonymous>)
      at C:\Users\neal\Projects\vite-test\node_modules\windicss\lib\index.js:9516:18
      at Array.map (<anonymous>)
      at Processor.wrapWithVariants (C:\Users\neal\Projects\vite-test\node_modules\windicss\lib\index.js:9511:23)
      at _gStyle (C:\Users\neal\Projects\vite-test\node_modules\windicss\lib\index.js:10120:37)
      at C:\Users\neal\Projects\vite-test\node_modules\windicss\lib\index.js:10147:53
      at Array.forEach (<anonymous>)
      at _loop_2 (C:\Users\neal\Projects\vite-test\node_modules\windicss\lib\index.js:10147:23)
      at Processor.attributify (C:\Users\neal\Projects\vite-test\node_modules\windicss\lib\index.js:10156:13)
```

and when hot update, Vite would raise similar error and exit
```sh
11:12:19 PM [vite] hmr update /src/App.vue
C:\Users\neal\Projects\vite-test\node_modules\windicss\lib\index.js:9516
                .map(function (i) { return _this._variants[i](); })
                                                             ^
TypeError: _this._variants[i] is not a function
    at C:\Users\neal\Projects\vite-test\node_modules\windicss\lib\index.js:9516:62
    at Array.map (<anonymous>)
    at C:\Users\neal\Projects\vite-test\node_modules\windicss\lib\index.js:9516:18
    at Array.map (<anonymous>)
    at Processor.wrapWithVariants (C:\Users\neal\Projects\vite-test\node_modules\windicss\lib\index.js:9511:23)
    at _gStyle (C:\Users\neal\Projects\vite-test\node_modules\windicss\lib\index.js:10120:37)
    at C:\Users\neal\Projects\vite-test\node_modules\windicss\lib\index.js:10147:53
    at Array.forEach (<anonymous>)
    at _loop_2 (C:\Users\neal\Projects\vite-test\node_modules\windicss\lib\index.js:10147:23)
    at Processor.attributify (C:\Users\neal\Projects\vite-test\node_modules\windicss\lib\index.js:10156:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Even if the team chooses not to support `group-hover`, it would be nice to throw a warning instead of an error in order to make Vite continue running.

Local version: 
```json
"vite-plugin-windicss": "^0.16.7",
"windicss": "^3.0.12"
```

btw, thanks for such a great framework!

**Comment by voorjaar** [comment]
should works in v3.1.1
