### ISSUE TITLE
Latest plugin version `1.4.11` not working with latests vite versions: `2.6.7` and `2.6.9`

### ISSUE THREAD

**Issue by userquin** [windicss/windicss#518]
Testing some issue on `vitesse` template I've found that using latest version of  vite `2.6.9` with latest `windicss`  plugin `1.4.11` the plugin fails on windows, I don't know if on another OS is also failing.

Downgrading to `vite 2.6.7` and `windicss 1.4.9` works.

I haven't test more combinations, maybe `vite 2.6.9` with `windicss 1.4.9` also works.

```shell
error when starting dev server:
Error: Cannot find module 'node:module'
Require stack:
- F:\work\projects\quini\GitHub\issue-210-vitesse-repo\node_modules\.pnpm\jiti@1.12.8\node_modules\jiti\dist\jiti.js
- F:\work\projects\quini\GitHub\issue-210-vitesse-repo\node_modules\.pnpm\jiti@1.12.8\node_modules\jiti\lib\index.js
- F:\work\projects\quini\GitHub\issue-210-vitesse-repo\node_modules\.pnpm\@windicss+config@1.4.11\node_modules\@windicss\config\dist\index.js
- F:\work\projects\quini\GitHub\issue-210-vitesse-repo\node_modules\.pnpm\@windicss+plugin-utils@1.4.11\node_modules\@windicss\plugin-utils\dist\index.js
- F:\work\projects\quini\GitHub\issue-210-vitesse-repo\node_modules\.pnpm\vite-plugin-windicss@1.4.11_vite@2.6.9\node_modules\vite-plugin-windicss\dist\index.js
- F:\work\projects\quini\GitHub\issue-210-vitesse-repo\vite.config.ts
- F:\work\projects\quini\GitHub\issue-210-vitesse-repo\node_modules\.pnpm\vite@2.6.9\node_modules\vite\dist\node\chunks\dep-be032392.js
- F:\work\projects\quini\GitHub\issue-210-vitesse-repo\node_modules\.pnpm\vite@2.6.9\node_modules\vite\dist\node\cli.js
- F:\work\projects\quini\GitHub\issue-210-vitesse-repo\node_modules\.pnpm\vite@2.6.9\node_modules\vite\bin\vite.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at F:\work\projects\quini\GitHub\issue-210-vitesse-repo\node_modules\.pnpm\jiti@1.12.8\node_modules\jiti\dist\jiti.js:1:51704
    at F:\work\projects\quini\GitHub\issue-210-vitesse-repo\node_modules\.pnpm\jiti@1.12.8\node_modules\jiti\dist\jiti.js:1:55809
    at Object.<anonymous> (F:\work\projects\quini\GitHub\issue-210-vitesse-repo\node_modules\.pnpm\jiti@1.12.8\node_modules\jiti\dist\jiti.js:1:55838)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
```
